### ISSUE TITLE
DRF request throttling ignored by LoginView

### ISSUE THREAD

**Issue by filipweidemann** [James1345/django-rest-knox#157] opened 2019-01-14 10:24 UTC
I just stumbled over an issue with the LoginView. Specifying global throttling classes and rates doesn't seem to stop the LoginView from accepting and processing requests anyway.
Even when creating custom throttling classes the same result happens.

Is this intended behaviour? Typically it shouldn't happen that a login view is not throttled..

**Comment by johnraz** [comment] 2019-01-14 19:03
Hello @filipweidemann,

This is definitely not the intended behaviour.

I'm a bit puzzled that the global throttling is not triggered as, at first glance, I don't see anything special in the `LoginView` that could avoid the throttling to work.

I would like to make sure that the issue lies with this library and is not a configuration issue.

Is the throttling working with other views than the login view?

Would you mind sharing some code to help reproduce the issue?

Code samples would be good but If you could setup a project demonstrating the issue or even better provide a PR with a failing test case, that would help a ton.

**Comment by belugame** [comment] 2019-01-14 20:16
I would also be surprised if knox affects drf throttling in any way. @filipweidemann the issue does not happen to you on drf's login view?

**Comment by filipweidemann** [comment] 2019-01-15 08:46
First of all, thanks for the quick responses.

@johnraz 
I already did the same, checked the `LoginView`, saw nothing out of the ordinary, so I started to limit the requests for anonymous users to `1/min` for easy testing. The result was that every single `APIView` was restricted, except the `LoginView`.

I created a sample project with just two views, one is the `LoginView`, the second one is a random `APIView` that just returns some content. 

@belugame 
I didn't know that DRF had built-in login views, so I can't say if that works or not.

I created a sample project with which you can easily reproduce the issue, have a look: https://github.com/filipweidemann/knox-throttling

**Comment by johnraz** [comment] 2019-01-15 10:58
Allright, thanks for the example project @filipweidemann it helped me a ton to get started and test this out.

I can confirm this is not related to knox.

A bit of context:
First we need to make it clear that there is authenticated and anonymous throttling playing a confusing game here...

In your project only anonymous throttling is enabled.
If you'd like to block someone from frenetically call the login view and get new tokens like crazy, you'd need to enable the authenticated throttling as well.

So I decided to ignore the above and consider only the case where you'd want to block someone that has no valid credentials and is trying to brute-force your login view.

At that stage, only the authentication middleware is relevant and not the login view at all.

How I came to this conclusion:

- hit the login view with credentials --> repeating the request doesn't trigger the throttle and it's expected behavior as we are dealing with anonymous user throttling only.

- hit the login view with bad credentials --> get a 401 back and this can be repeated as much as we can, this is not the expected behaviour.

- change the definition of the `ThrottledReferenceView` to
```
class ThrottledReferenceView(APIView):
    authentication_classes = [BasicAuthentication]
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        return Response(data={"content": "request was valid."})
```
now hit the view with bad credentials --> get a 401 back and this can be repeated again without triggering the throttling.

So we can see the same behavior for both views.
My best bet is it's due to the permission being executed before the throttling check in order to allow authenticated throttling vs anonymous throttling:

see the three last lines: 
https://github.com/encode/django-rest-framework/blob/903204cd7926e9e6ceaaec1bfbf1ba3ed3330ca4/rest_framework/views.py#L385-L402

```
    def initial(self, request, *args, **kwargs):
        """
        Runs anything that needs to occur prior to calling the method handler.
        """
        self.format_kwarg = self.get_format_suffix(**kwargs)


        # Perform content negotiation and store the accepted info on the request
        neg = self.perform_content_negotiation(request)
        request.accepted_renderer, request.accepted_media_type = neg


        # Determine the API version, if versioning is in use.
        version, scheme = self.determine_version(request, *args, **kwargs)
        request.version, request.versioning_scheme = version, scheme


        # Ensure that the incoming request is permitted
        self.perform_authentication(request)
        self.check_permissions(request)
        self.check_throttles(request)
```

@filipweidemann : you can ask around in DJRF's issue tracker but I'm pretty sure this done by design.
@belugame I think we can close this.

**Comment by belugame** [comment] 2019-01-15 11:02
Funny coincidence this came up just when we are discussing throttling

**Closed by belugame** 2019-01-15 11:02 UTC
Labels: invalid

**Comment by filipweidemann** [comment] 2019-01-15 11:11
Was already expecting something like that, thanks you for having a look @johnraz!

**Comment by johnraz** [comment] 2019-01-15 11:12
Very welcome, I benefit from this as well as I learnt something about DJRF's internal 👍
