### ISSUE TITLE
Why are there two non-auth exit strategies?

### ISSUE THREAD

**Issue by pupeno** [James1345/django-rest-knox#166] opened 2019-02-07 14:06 UTC
In the [authenticate method](https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L41) there are two potential exits: returning `None` or raising an exception:

- https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L46
- https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L49
- https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L53
- https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L56

When returning `None`, an API class that looks like this:

```python
class LogInView(GenericAPIView):
  authentication_classes = (TokenAuthentication,)
  permission_classes = (AllowAny,)
    
  def post(self, request, *args, **kwargs):
    pass # do something
```

works, but when raising an exception, the `get`  method never gets executed. This means that a custom `LogIn` class cannot authenticate a user if for some reason the user ended up with a broken Token as it would be [on line 49](https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L49).

I made a personal copy of Knox to make some other changes, but one of the changes I did was to standardize on always returning None. It seems to work just fine in marking the request as not authenticated and thus classes defined like this:

```python
class ChangePasswordView(APIView):
  authentication_classes = (TokenAuthentication,)
  permission_classes = (IsAuthenticated,)
    
  def post(self, request, *args, **kwargs):
    pass # do something
```

work as expected in the requirement of authentication.

I intend to make a PR request with my improvements to Knox, but I would need to clarify whether this behavior is intended or a bug, to see how I turn my own version of Knox into a contribution to this one.

**Comment by johnraz** [comment] 2019-02-07 15:11
The reason why the `authenticate` method either returns `None` or `AuthenticationFailed` is to allow  multiple authentication type to co-exist (eg: basic-auth and token-auth). 

Once a header matching the authentication type is found, we know that the authentication has been selected and anything passing that point should either fail by raising an exception or succeed by login the user in. 

If the header is not found, we return `None` to indicate that the next authentication type should be attempted.

This is how Django Rest Framework is implemented and is not specific to knox ([code is here](https://github.com/encode/django-rest-framework/blob/dc6b3bf42e53c6bfdb597a67de931913c8bd0255/rest_framework/authentication.py#L173-L192
)).


> This means that a custom `LogIn` class cannot authenticate a user if for some reason the user ended up with a broken Token

What you define has a "broken token" is instead a token that doesn't validate the prefix, prefix that is used to detect that knox should be used as the authentication method for the request.

> one of the changes I did was to standardize on always returning None

By doing this we would miss all the token validation related to knox's token which I think is bad.

> when raising an exception, the `get` method never gets executed.

I don't get what you mean by this, the get method shouldn't be executed if the authentication fails anyway, right?


I hope this helps you clarify the situation, if I missed a point in your question, let me know.

**Comment by pupeno** [comment] 2019-02-07 15:23
In this case:

```python
class LogInView(GenericAPIView):
  authentication_classes = (TokenAuthentication,)
  permission_classes = (AllowAny,)
    
  def post(self, request, *args, **kwargs):
    pass # do something
```

the method `post` should always run, even if the token, for some reason, is invalid; as it is the method by which a new token can be issued. But if the token is there and it's working and authenticated, that's a valuable state as well. In the current knox, if the token is invalid and it raises an exception, that user can't ever log in again without having a developer call them on the phone and explain to them how to purge stored data in the browser.

**Comment by johnraz** [comment] 2019-02-07 18:18
Ah! I overlooked the fact that we were talking about the Login view.

I take back the fact that the method shouldn't be reachable if authentication fails as it's actually part of the authentication process.
That being said, apart from that detail, my explanation still holds true.

If you issue a request with an invalid token on the login view, the token check will take precedence on the actual login action and fail with an `AuthenticationFailed` exception and hence stop processing of the request and return an appropriate response.

I understand this is not exactly the behaviour you'd like to see but again, this is by design in Django Rest Framework. 

I'm not keen at all to have a "never raise" policy here as it would raise (hum 😄) more issues than it would solve.

Now that I have a bit more insight of what your issue is, I think your problem lies on the client side.

A user that wants to log in, should be in logged out state to being with.
If he's logged out, then the session on the client side should be cleaned out.
There should be no trace of the token anymore on the client's cache.

Actually as soon as the client gets an authentication failed error from the server, whenever it does any kind of request, it should clean every token it has and try to login again.

So I would argue that the situation you describe is a consequence of a bad design / coding practice on the client side.

Also as you bring the "how to purge stored data in the browser", I would recommend you to read [this discussion](https://spectrum.chat/react?thread=b26fbe1f-b816-44f4-84ce-b21faf219802) I started a few days ago about storing a token in the browser regarding security. You should definitely tell your users to not store the token in the browser at any cost but use a good old cookie + session-id instead. I know it's a common misconception as every tutorial / blog post / documentation around shows that you can store the token in localstorage or a cookie easily but it's highly insecure...

**Comment by johnraz** [comment] 2019-02-10 21:45
@belugame I would close this, @pupeno if you find I didn't properly address your question, please re-open.

**Closed** 2019-02-12 05:43 UTC
